version: '3.10'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - ./core:/usr/src/app
#      - /home/webapps/tender_v2/staticfiles:/usr/src/app/staticfiles
#      - /home/webapps/tender_v2/mediafiles:/usr/src/app/mediafiles
#    environment:
#      SQL_HOST: "bd"
    ports:
      - "8010:8000"
    env_file: env.dev
#  bd:
#    restart: always
#    image: library/postgres:12-alpine
#    environment:
#      - DEBUG=1
#      - POSTGRES_PASSWORD=1962639196
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=tender_db
#      - CELERY_BROKER_URL=redis://redis:6379/0
#      - CELERY_RESULT_BACKEND=redis://redis:6379/0
#    ports:
#      - "5433:5432"