version: '3.10'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - bd
    environment:
      SQL_HOST: "bd"
    ports:
      - "8010:8000"
    env_file: env.dev
  bd:
    restart: always
    image: library/postgres:12-alpine
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    env_file: env.dev
    ports:
      - "5433:5432"

volumes:
  postgres_data: