# Generated by Django 4.1.5 on 2023-01-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.CharField(max_length=400)),
                ('is_active', models.BooleanField(default=True)),
                ('clicks', models.IntegerField()),
                ('url', models.CharField(max_length=400)),
            ],
        ),
    ]
